# Версия конфигурации, не изменять.
version: ${hcore.version.config}

# Конфигурация плагина.
settings:

    #   ▄▄█▀▀▀▄█                                                    ▀██         
    # ▄█▀     ▀    ▄▄▄   ▄▄ ▄▄ ▄▄   ▄▄ ▄▄ ▄▄    ▄▄▄▄   ▄▄ ▄▄▄     ▄▄ ██   ▄▄▄▄  
    # ██         ▄█  ▀█▄  ██ ██ ██   ██ ██ ██  ▀▀ ▄██   ██  ██  ▄▀  ▀██  ██▄ ▀  
    # ▀█▄      ▄ ██   ██  ██ ██ ██   ██ ██ ██  ▄█▀ ██   ██  ██  █▄   ██  ▄ ▀█▄▄ 
    #  ▀▀█▄▄▄▄▀   ▀█▄▄█▀ ▄██ ██ ██▄ ▄██ ██ ██▄ ▀█▄▄▀█▀ ▄██▄ ██▄ ▀█▄▄▀██▄ █▀▄▄█▀ 

    # Отправка команд игроком.
    send-command:

        # Блокировка всех команд через двоеточие. (пример /essentials:gamemode)
        disable-colon: true

        # Запретить все команды
        disable-commands: false

        # Команды от этого плагина.
        plugin:
            # Их можно удалять.
            # Чтобы удалить все команды используй commands: []
            commands:
                spawn:
                    aliases:
                        - spavn
                        - ызфцт
                        - ызфмт
                setspawn:
                    aliases: []
                hreload:
                    aliases: []
                crash:
                    aliases: []
                clearchat:
                    aliases:
                        - сдуфксрфе
                prefix:
                    data:
                        # Максимальный лимит символов в строке.
                        max-limit: 16
                    aliases:
                        - зкуашч
                free:
                    data:
                        # Команда которая будет выполняться от имени консоли при получении ключа.
                        command: "/crazycrates give virtual Free 1 {player}"
                    aliases:
                        - акуу
                        - freecase
                        - casefree
                        - акуусфыу
                        - сфыуакуу
            format: "&a/{command} {arguments} &f- {description}"


        # Список разрешённых команд которые будут отправлены в любом случае игнорируя все проверки.
        whitelist: []

    # ▀██    ██▀                                                      
    #  ███  ███    ▄▄▄▄   ▄▄▄▄   ▄▄▄▄   ▄▄▄▄     ▄▄▄ ▄   ▄▄▄▄   ▄▄▄▄  
    #  █▀█▄▄▀██  ▄█▄▄▄██ ██▄ ▀  ██▄ ▀  ▀▀ ▄██   ██ ██  ▄█▄▄▄██ ██▄ ▀  
    #  █ ▀█▀ ██  ██      ▄ ▀█▄▄ ▄ ▀█▄▄ ▄█▀ ██    █▀▀   ██      ▄ ▀█▄▄ 
    # ▄█▄ █ ▄██▄  ▀█▄▄▄▀ █▀▄▄█▀ █▀▄▄█▀ ▀█▄▄▀█▀  ▀████▄  ▀█▄▄▄▀ █▀▄▄█▀ 
    #                                          ▄█▄▄▄▄▀                

    # Отправка сообщений игроком.
    send-message:

        # При отправке сообщения которое начинается с # будет отправлена команда в консоль.
        # Пример #gm 1 deHasher.
        # Штука слишком опасная и доступна только тем, кто есть в списке admins в main.yml
        hidden-console:
            enabled: true
            cmd: "#"

        # Отключить возможность писать в чат.
        disable-messages: false

        # Задержка на сообщения.
        cooldown:
            enabled: false

            # Время в секундах.
            time: 2
        
        # Модификация сообщений. (пока что малофункциональна)
        modify:
            enabled: false

            # Поддерживаются заполнители из файла с переводом.
            format: "{main}&a{player}&c ➥&f {message}"

    #     █         ▀██                             ▄    ██                                               ▄   
    #    ███      ▄▄ ██  ▄▄▄▄ ▄▄▄   ▄▄▄▄  ▄▄▄ ▄▄  ▄██▄  ▄▄▄   ▄▄▄▄    ▄▄▄▄  ▄▄ ▄▄ ▄▄     ▄▄▄▄  ▄▄ ▄▄▄   ▄██▄  
    #   █  ██   ▄▀  ▀██   ▀█▄  █  ▄█▄▄▄██  ██▀ ▀▀  ██    ██  ██▄ ▀  ▄█▄▄▄██  ██ ██ ██  ▄█▄▄▄██  ██  ██   ██   
    #  ▄▀▀▀▀█▄  █▄   ██    ▀█▄█   ██       ██      ██    ██  ▄ ▀█▄▄ ██       ██ ██ ██  ██       ██  ██   ██   
    # ▄█▄  ▄██▄ ▀█▄▄▀██▄    ▀█     ▀█▄▄▄▀ ▄██▄     ▀█▄▀ ▄██▄ █▀▄▄█▀  ▀█▄▄▄▀ ▄██ ██ ██▄  ▀█▄▄▄▀ ▄██▄ ██▄  ▀█▄▀ 

    # Проверка на рекламу.
    fix-advertisement:
        enabled: true

        # Регулярное выражение для проверки строки на наличие в ней домена.
        regex: '[-a-zA-Zа-яА-Я0-9@:%_\+.~#?&//=]{2,256}\.[a-zA-Z]{2,4}\b(\/[-a-zA-Zа-яА-Я0-9@:%_\+~#?&//=]*)?'

        # На что будет заменено слово которое содержит запрещённый домен.
        replacement: "lostmine.ru" # Только для табличек пока что...

        # Что необходимо проверять на рекламу?
        checks:
            items: true
            signs: true
            messages: true
            commands: true

        # Список разрешённых сайтов.
        # Указывать только домены.
        # При разрешённом домене vk.com будет доступна сслыка по типу https://www.vk.com/dehasher
        whitelist:
          - "lostmine.ru"
          - "vk.com"
          - "youtube.com"
          - "google.com"
          - "spigotmc.org"
          - "dehasher.ru"
          - "yandex.ru"
          - "github.com"
          - "klauncher.ru"
          - "klaun.ch"

    # ▀██▀▀▀▀█                   ▀██           ██    ▄          
    #  ██  ▄    ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄   ██    ▄▄▄   ▄▄▄  ▄██▄   ▄▄▄▄  
    #  ██▀▀█     ▀█▄▄▀   ██▀  ██  ██  ▄█  ▀█▄  ██   ██   ██▄ ▀  
    #  ██         ▄█▄    ██    █  ██  ██   ██  ██   ██   ▄ ▀█▄▄ 
    # ▄██▄▄▄▄▄█ ▄█  ██▄  ██▄▄▄▀  ▄██▄  ▀█▄▄█▀ ▄██▄  ▀█▄▀ █▀▄▄█▀ 
    #                    ██                                     
    #                   ▀▀▀▀                                    

    # Исправление эксплойтов сервера.
    fix-exploits:

        # Краш сервера шалкером + раздатчиком на 256 высоте. (только на 1.12)
        dispenser: true

        # Краш сервера с помощью быстрого перемещения предметов в слотах.
        swap: true

        # Исправление чанк бана.
        chunk-ban:
            enabled: true
            max:
                blocks: 512
                heads: 100
            blocks:
                - FURNACE
                - TRAPPED_CHEST
                - ENCHANTMENT_TABLE
                - STANDING_BANNER
                - WALL_BANNER
                - WALL_SIGN
                - SIGN_POST
                - HOPPER
                - DROPPER
                - DISPENSER
                - BREWING_STAND
                - BEACON
                - ENDER_CHEST
                - FLOWER_POT
                - BANNER
            heads:
                - SKULL_ITEM
                - SKULL
            frame: ITEM_FRAME

        # Блокировка открытия инвенторя и ввода команд во время сна.
        bed:
            disable-inventory: true
            disable-commands: true

        # Обработка телепортаций через порталы.
        portal-teleporting:

            # Включить точку спавна портала в АД.
            # Точка спавна устанавливается с помощью команды /setspawn nether
            # Необходимо для того, чтобы снизить нагрузку на сервер при телепортациях так
            # как при каждой телепортации происходит эвент поиска ближайшего портала
            # и этим самым сильно нагружает сервер.
            enable-nether-spawn: true

            # Блокировка телепортации сущностей через порталы.
            block-entity-teleport: true

        # Возвращение в норму предметов у которых нелегальный стак. Пример: 64 тотема.
        overstack:
            enabled: true

            # Список предметов которые могут иметь бесконечный стак.
            whitelist:
            - RABBIT_STEW
            - MUSHROOM_SOUP
            - BEETROOT_SOUP
            - CAKE

        # Заменяет предметы с большим количеством байт на блок земли.
        items:
            enabled: true
            limit-bytes: 4200
            shulker:
                limit-bytes: 14000
                block-books: true
                block-nested: false

    #    ▀██▀          ██                  ▄█▀▀▀▄█                                           
    #     ██    ▄▄▄   ▄▄▄  ▄▄ ▄▄▄          ██▄▄  ▀    ▄▄▄▄  ▄▄▄ ▄▄  ▄▄▄▄ ▄▄▄   ▄▄▄▄  ▄▄▄ ▄▄  
    #     ██  ▄█  ▀█▄  ██   ██  ██          ▀▀███▄  ▄█▄▄▄██  ██▀ ▀▀  ▀█▄  █  ▄█▄▄▄██  ██▀ ▀▀ 
    #     ██  ██   ██  ██   ██  ██   ████ ▄     ▀██ ██       ██       ▀█▄█   ██       ██     
    # ██ ▄█▀   ▀█▄▄█▀ ▄██▄ ▄██▄ ██▄       █▀▄▄▄▄█▀   ▀█▄▄▄▀ ▄██▄       ▀█     ▀█▄▄▄▀ ▄██▄    
    #  ▀▀▀                                                                                   

    # Подключение игрока к серверу.
    join-server:

        # Изменение цвета ников.
        custom-nickname:
            enabled: false
            color:
                users: "&a"
                admins: "&c"
            disable-collisions: false

        # Всегда устанавливать максимальное количество хп.
        always-set-max-hp: false

        # Телепортация к спавну при заходе на сервер.
        spawn:

            # Телепортировать игрока на спавн при первом заходе на сервер.
            first: true

            # Телепортировать игрока на спавн каждый раз когда он заходит на сервер.
            always: false

        # Деопать всех игроков (и ленивых админов) которые не снимают с себя опку после того, как выходят с сервера.
        auto-deop: true

        # Флай при заходе на сервер.
        auto-fly: false

    # ▀██▀▀█▄             ▄              ▄          
    #  ██   ██   ▄▄▄▄   ▄██▄  ▄▄▄ ▄▄▄  ▄██▄   ▄▄▄▄  
    #  ██▀▀▀█▄  ▀▀ ▄██   ██    ██  ██   ██   ██▄ ▀  
    #  ██    ██ ▄█▀ ██   ██    ██  ██   ██   ▄ ▀█▄▄ 
    # ▄██▄▄▄█▀  ▀█▄▄▀█▀  ▀█▄▀  ▀█▄▄▀█▄  ▀█▄▀ █▀▄▄█▀ 

    # Настройка прыжков на блоках.
    batuts:

        # Необходим перезапуск сервера для включения/выключения этой функции.
        enabled: true

        # Вектор высоты и направления.
        vector:
            height: 3.5
            direction: 1

        # Настройка типов блоков для создания батута.
        block:
            up: STONE_PLATE
            down: DIAMOND_BLOCK

        # Звук при прыжке на батуте.
        sound:
            enabled: true
            play: ENTITY_ENDERDRAGON_FLAP

    # ▀██▀▀█▄                     ▄   ▀██
    #  ██   ██    ▄▄▄▄   ▄▄▄▄   ▄██▄   ██ ▄▄
    #  ██    ██ ▄█▄▄▄██ ▀▀ ▄██   ██    ██▀ ██
    #  ██    ██ ██      ▄█▀ ██   ██    ██  ██
    # ▄██▄▄▄█▀   ▀█▄▄▄▀ ▀█▄▄▀█▀  ▀█▄▀ ▄██▄ ██▄

    # Смерть игрока.
    death:

        # Телепортировать игрока на спавн.
        teleport-to-spawn: true

        # Шанс дропа предметов после смерти.
        # Необходим перезапуск сервера для включения/выключения этой функции.
        chance-on-drop-items:
            enabled: false

            # 0.5 = 50%
            chance:
                item: 0.5
                exp: 0.5

            # Список игнорируемых миров в которых всегда выпадают все предметы.
            ignored-worlds: []

    #  ▄█▀▀▀▄█                                        ▀██▀▀▀▀█                  
    #  ██▄▄  ▀  ▄▄▄ ▄▄▄   ▄▄▄▄   ▄▄▄ ▄▄▄ ▄▄▄ ▄▄ ▄▄▄    ██  ▄      ▄▄▄ ▄   ▄▄▄ ▄ 
    #   ▀▀███▄   ██▀  ██ ▀▀ ▄██   ██  ██  █   ██  ██   ██▀▀█     ██ ██   ██ ██  
    # ▄     ▀██  ██    █ ▄█▀ ██    ███ ███    ██  ██   ██         █▀▀     █▀▀   
    # █▀▄▄▄▄█▀   ██▄▄▄▀  ▀█▄▄▀█▀    █   █    ▄██▄ ██▄ ▄██▄▄▄▄▄█  ▀████▄  ▀████▄ 
    #            ██                                             ▄█▄▄▄▄▀ ▄█▄▄▄▄▀ 
    #           ▀▀▀▀                                                            

    # Задержка при использовании яйца призыва моба.
    cooldown-on-use-spawnegg:

        # Необходим перезапуск сервера для включения/выключения этой функции.
        enabled: true

        # Время в секундах.
        time: 30

    # ▀██▀▀█▄           ▀██▀▀█▄            █
    #  ██   ██ ▄▄▄▄ ▄▄▄  ██   ██          ███    ▄▄▄ ▄▄    ▄▄▄▄  ▄▄ ▄▄▄    ▄▄▄▄
    #  ██▄▄▄█▀  ▀█▄  █   ██▄▄▄█▀         █  ██    ██▀ ▀▀ ▄█▄▄▄██  ██  ██  ▀▀ ▄██
    #  ██        ▀█▄█    ██       ████  ▄▀▀▀▀█▄   ██     ██       ██  ██  ▄█▀ ██
    # ▄██▄        ▀█    ▄██▄           ▄█▄  ▄██▄ ▄██▄     ▀█▄▄▄▀ ▄██▄ ██▄ ▀█▄▄▀█▀

    # Настройка пвп-арены.
    # Необходим плагин WorldGuard и WorldEdit.
    pvp-arena:

        # Необходим перезапуск сервера для включения/выключения этой функции.
        enabled: true

        # Регион пвп-арены.
        regions:
            - "pvp:world"

        # Блокировка возможностей игроков на арене.
        block:
            fly: true
            godmode: true # Необходим Essentials.
            gadgets: true # Необходим GadgetsMenu.
            commands: true
            gamemodes:
                - CREATIVE
                - ADVENTURE

        # Удаление предметов у игроков во время пвп.
        clear-custom-items:
            enabled: true
            item-names:
                - "&a» &fМеню &a«"

        # Список разрешённых команд которые можно вводить в регионе.
        whitelist-commands:
            - "/spawn"
            - "/spavn"
            - "/ызфцт"
            - "/ызфмт"
            - "/warp выход-с-пвп"
            - "/message"
            - "/msg"
            - "/tell"
            - "/t"
            - "/pm"
            - "/m"
            - "/w"
            - "/whisper"

        # Список разрешённых команд которые можно вводить другим игрокам
        # направленные на игрока который находится на пвп арене.
        whitelist-other-commands:
            - "/ban"
            - "/mute"
            - "/warn"
            - "/ифт"
            - "/ьгеу"
            - "/цфкт"
            - "/spawnmob"
            - "/enchant"
            - "/утсрфте"
            - "/ызфцтьщи"
            - "/message"
            - "/msg"
            - "/tell"
            - "/t"
            - "/pm"
            - "/m"
            - "/w"
            - "/whisper"

        # Список аргументов у команд которые могут вводить игроки когда ник какого-то
        # игрока совпадает с аргументом.
        whitelist-other-arguments:
            - "all"
            - "hand"
            - "day"
            - "night"
            - "walk"
            - "fly"
            - "add"
            - "msg"
            - "message"
            - "i"
            - "inspect"
            - "clear"
            - "p"
            - "chat"
            - "tab"

    #   ▄▄█▀▀▀▄█                    ▀██                ▄
    # ▄█▀     ▀    ▄▄▄   ▄▄ ▄▄ ▄▄    ██ ▄▄▄   ▄▄▄▄   ▄██▄
    # ██         ▄█  ▀█▄  ██ ██ ██   ██▀  ██ ▀▀ ▄██   ██
    # ▀█▄      ▄ ██   ██  ██ ██ ██   ██    █ ▄█▀ ██   ██
    #  ▀▀█▄▄▄▄▀   ▀█▄▄█▀ ▄██ ██ ██▄  ▀█▄▄▄▀  ▀█▄▄▀█▀  ▀█▄▀

    combat:
        # Фейковые анимации ударов.
        # Необходим ProtocolLib.
        fake-damage-animation: true

        # Эффекты крови.
        blood:
            enabled: true
            effect: REDSTONE_WIRE

    #  ▄▄█▀▀▀▄█            ██  ▀██      ▀██
    # ▄█▀     ▀  ▄▄▄ ▄▄▄  ▄▄▄   ██    ▄▄ ██   ▄▄▄▄
    # ██    ▄▄▄▄  ██  ██   ██   ██  ▄▀  ▀██  ██▄ ▀
    # ▀█▄    ██   ██  ██   ██   ██  █▄   ██  ▄ ▀█▄▄
    #  ▀▀█▄▄▄▀█   ▀█▄▄▀█▄ ▄██▄ ▄██▄ ▀█▄▄▀██▄ █▀▄▄█▀

    # Исправление гильдий.
    guilds-fix:
        enabled: true
        commands: guild|guilds|g|c|clan|clans|п|пгшдв|пгшдвы|с|сдфт|сдфты
        prefix: "&8&m━━━━━━━━━━━━━━━━━━&8[ &cГильдии &8]&8&m━━━━━━━━━━━━━━━━━━"
        roles:
            все: |-
                &a/guild list &f- Список всех гильдий.
                &a/guild create &7[&aназвание&7] &f- Создать гильдию. &7(€3.000.000)
                &a/guild request &f- Отправить запрос на вступление в гильдию.
                &a/guild code redeem &7[&aкод&7] &f- Использовать пригласительный код.
            участник: |-
                &a/guild info &f- Информация о Вашей гильдии.
                &a/guild bank &f- Банк гильдии.
                &a/guild chat &f- Переключить режим чата гильдии.
                &a/guild home &f- Телепортироваться в дом гильдии.
                &a/guild members &f- Список участников гильдии.
                &a/guild leave &f- Покинуть гильдию.
            старейшина: |-
                &b/guild invite &7[&bник&7] &f- Пригласить игрока в гильдию.
            хранитель: |-
                &6/guild buff &f- Открыть меню баффов гильдии.
                &6/guild vault &f- Открыть склад гильдии.
                &6/guild motd &7[&6set&7/&6remove&7] &f- Изменить приветствие клана.
                &6/guild code &f- Пригласительные коды гильдии.
            соруководитель: |-
                &e/guild ally &f- Гильдейские союзы.
                &e/guild war &f- Гильдейские войны.
                &e/guild sethome &f- Установить точку дома гильдии. &7(€500.000)
                &e/guild promote &7[&eник&7] &f- Повысить роль игрока в гильдии.
                &e/guild demote &7[&eник&7] &f- Понизить роль игрока в гильдии.
                &e/guild kick &7[&eник&7] &f- Выгнать игрока из гильдии.
                &e/guild upgrade &f- Повысить уровень гильдии.
            глава: |-
                &d/guild delete &f- Расформировать гильдию.
                &d/guild status &f- Переключить статус гильдии.
                &d/guild rename &7[&dназвание&7] &f- Переименовать гильдию.
                &d/guild transfer &7[&dник&7] &f- Передать владение гильдией другому игроку.

    #  ▄▄█▀▀██     ▄   ▀██
    # ▄█▀    ██  ▄██▄   ██ ▄▄     ▄▄▄▄  ▄▄▄ ▄▄  
    # ██      ██  ██    ██▀ ██  ▄█▄▄▄██  ██▀ ▀▀ 
    # ▀█▄     ██  ██    ██  ██  ██       ██     
    #  ▀▀█▄▄▄█▀   ▀█▄▀ ▄██▄ ██▄  ▀█▄▄▄▀ ▄██▄    

    # Остальные параметры.
    other-params:
        # Возможность писать на табличках используя цветовые теги &1 &2 &3 и т.д.
        colored-signs: true

        # Права hcore.bypass.* перестанут работать.
        # Рекомендуется держать включённым на серверах авторизации и хаба.
        disable-bypass-permissions: false

        # Кастомное количество здоровья всем игрокам.
        custom-health:
            enabled: false

            # health: 20 - 10 сердечек.
            health: 20

        # Время в тиках для отправки запросов на сервер плагином о проверке всех игроков.
        # timer: 60 - 3 секунды.
        # Значение лучше ставить не меньше 20-30.
        # При просадках TPS это значение можно увеличить. (Бывает если онлайн больше 200)
        # Проверяются: PvP-Arena, Overstack-Items, Custom-Health. (если они конечно включены)
        timer: 60

        # Блокировка различных действий игроков...
        block-actions:

            # Телепортация через /gm 3.
            spectate-teleport: true

            # Запретить игрокам видеть других игроков.
            see-other-players: false

            # Выключить звук создания портала в ЭНД. (его слышат все игроки на сервере)
            # Необходим ProtocolLib.
            end-portal-sound: true

            # Блокировать использование спавнеров. Можно только админам.
            use-spawners: true

            # Запрещать игроку находиться выше 1000 и ниже -1000 координаты по Y.
            invalid-location: true

        # Скрытие сообщений о подключениях, ачивках и т.д. игроков.
        hide-messages:
            join: true
            leave: true
            death: true
            advancements: true

        # Больше информации можно узнать тут: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/Cancellable.html
        disable-events:

            # Необходим перезапуск сервера для включения/выключения этой функции.
            enabled: false

            # Список доступных для отключения эвентов.
            list:
                PlayerInteractEvent: false
                BlockBreakEvent: false
                WeatherChangeEvent: false
                BlockPlaceEvent: false
                EntityDamageEvent: false
                PlayerInteractEntityEvent: false
                PlayerDropItemEvent: false
                EntityPickupItemEvent: false
                BlockFadeEvent: false
                BlockPhysicsEvent: false
                BlockFromToEvent: false
                BlockBurnEvent: false
                BlockIgniteEvent: false
                BlockSpreadEvent: false
                FoodLevelChangeEvent: false
                EntityExplodeEvent: false
                StructureGrowEvent: false
                PlayerChatTabCompleteEvent: false
                BlockFormEvent: false
                CreatureSpawnEvent: false
                LeavesDecayEvent: false