# Версия конфигурации, не изменять.
version: 0.3

# Конфигурация плагина.
settings:

    #   ▄▄█▀▀▀▄█                                                    ▀██         
    # ▄█▀     ▀    ▄▄▄   ▄▄ ▄▄ ▄▄   ▄▄ ▄▄ ▄▄    ▄▄▄▄   ▄▄ ▄▄▄     ▄▄ ██   ▄▄▄▄  
    # ██         ▄█  ▀█▄  ██ ██ ██   ██ ██ ██  ▀▀ ▄██   ██  ██  ▄▀  ▀██  ██▄ ▀  
    # ▀█▄      ▄ ██   ██  ██ ██ ██   ██ ██ ██  ▄█▀ ██   ██  ██  █▄   ██  ▄ ▀█▄▄ 
    #  ▀▀█▄▄▄▄▀   ▀█▄▄█▀ ▄██ ██ ██▄ ▄██ ██ ██▄ ▀█▄▄▀█▀ ▄██▄ ██▄ ▀█▄▄▀██▄ █▀▄▄█▀ 

    # Отправка команд игроком.
    send-command:
        # Блокировка всех команд через двоеточие. (пример /essentials:gamemode)
        disable-colon: true

        # Запретить все команды
        disable-commands: false

        # Команды от этого плагина.
        plugin:
            # Их можно удалять.
            # Чтобы удалить все команды используй commands: []
            commands:
                spawn:
                    aliases:
                        - spavn
                        - ызфцт
                        - ызфмт
                setspawn:
                    aliases: []
                hreload:
                    aliases: []
            format: "&a/{command} {arguments} &f- {description}"


        # Список разрешённых команд. Работает только когда disable-commands: true
        whitelist: []

    # ▀██    ██▀                                                      
    #  ███  ███    ▄▄▄▄   ▄▄▄▄   ▄▄▄▄   ▄▄▄▄     ▄▄▄ ▄   ▄▄▄▄   ▄▄▄▄  
    #  █▀█▄▄▀██  ▄█▄▄▄██ ██▄ ▀  ██▄ ▀  ▀▀ ▄██   ██ ██  ▄█▄▄▄██ ██▄ ▀  
    #  █ ▀█▀ ██  ██      ▄ ▀█▄▄ ▄ ▀█▄▄ ▄█▀ ██    █▀▀   ██      ▄ ▀█▄▄ 
    # ▄█▄ █ ▄██▄  ▀█▄▄▄▀ █▀▄▄█▀ █▀▄▄█▀ ▀█▄▄▀█▀  ▀████▄  ▀█▄▄▄▀ █▀▄▄█▀ 
    #                                          ▄█▄▄▄▄▀                

    # Отправка сообщений игроком.
    send-message:
        # При отправке сообщения которое начинается с # будет отправлена команда в консоль.
        # Пример #gm 1 deHasher.
        # Штука слишком опасная и доступна только тем, кто есть в списке admins в main.yml
        hidden-console:
            enabled: true
            cmd: "#"

        # Отключить возможность писать в чат.
        disable-messages: false

        # Задержка на сообщения.
        cooldown:
            enabled: false

            # Время в секундах.
            time: 2
        
        # Модификация сообщений. (пока что малофункциональна)
        modify:
            enabled: false

            # Поддерживаются заполнители из файла с переводом.
            format: "{main}&a{player}&c ➥&f {message}"

    #     █         ▀██                             ▄    ██                                               ▄   
    #    ███      ▄▄ ██  ▄▄▄▄ ▄▄▄   ▄▄▄▄  ▄▄▄ ▄▄  ▄██▄  ▄▄▄   ▄▄▄▄    ▄▄▄▄  ▄▄ ▄▄ ▄▄     ▄▄▄▄  ▄▄ ▄▄▄   ▄██▄  
    #   █  ██   ▄▀  ▀██   ▀█▄  █  ▄█▄▄▄██  ██▀ ▀▀  ██    ██  ██▄ ▀  ▄█▄▄▄██  ██ ██ ██  ▄█▄▄▄██  ██  ██   ██   
    #  ▄▀▀▀▀█▄  █▄   ██    ▀█▄█   ██       ██      ██    ██  ▄ ▀█▄▄ ██       ██ ██ ██  ██       ██  ██   ██   
    # ▄█▄  ▄██▄ ▀█▄▄▀██▄    ▀█     ▀█▄▄▄▀ ▄██▄     ▀█▄▀ ▄██▄ █▀▄▄█▀  ▀█▄▄▄▀ ▄██ ██ ██▄  ▀█▄▄▄▀ ▄██▄ ██▄  ▀█▄▀ 

    # Проверка на рекламу.
    fix-advertisement:
        enabled: true

        # Регулярное выражение для проверки строки на наличие в ней домена.
        regex: '[-a-zA-Zа-яА-Я0-9@:%_\+.~#?&//=]{2,256}\.[a-zA-Z]{2,4}\b(\/[-a-zA-Zа-яА-Я0-9@:%_\+~#?&//=]*)?'

        # На что будет заменено слово которое содержит запрещённый домен.
        replacement: "lostmine.ru" # Только для табличек пока что...

        # Что необходимо проверять на рекламу?
        checks:
            items: true
            signs: true
            messages: true
            commands: true

        # Список разрешённых сайтов.
        # Указывать только домены.
        # При разрешённом домене vk.com будет доступна сслыка по типу https://www.vk.com/dehasher
        whitelist:
          - "lostmine.ru"
          - "vk.com"
          - "youtube.com"
          - "google.com"
          - "spigotmc.org"
          - "dehasher.ru"
          - "yandex.ru"
          - "github.com"
          - "klauncher.ru"
          - "klaun.ch"

    # ▀██▀▀▀▀█                   ▀██           ██    ▄          
    #  ██  ▄    ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄   ██    ▄▄▄   ▄▄▄  ▄██▄   ▄▄▄▄  
    #  ██▀▀█     ▀█▄▄▀   ██▀  ██  ██  ▄█  ▀█▄  ██   ██   ██▄ ▀  
    #  ██         ▄█▄    ██    █  ██  ██   ██  ██   ██   ▄ ▀█▄▄ 
    # ▄██▄▄▄▄▄█ ▄█  ██▄  ██▄▄▄▀  ▄██▄  ▀█▄▄█▀ ▄██▄  ▀█▄▀ █▀▄▄█▀ 
    #                    ██                                     
    #                   ▀▀▀▀                                    

    # Исправление эксплойтов сервера.
    fix-exploits:
        # Краш сервера шалкером + раздатчиком на 256 высоте. (только на 1.12)
        dispenser: true

        # Краш сервера с помощью быстрого перемещения предметов в слотах.
        swap: true

        # Блокировка открытия инвенторя и ввода команд во время сна.
        bed:
            disable-inventory: true
            disable-commands: true

        # Обработка телепортаций через порталы.
        portal-teleporting:

            # Включить точку спавна портала в АД.
            # Точка спавна устанавливается с помощью команды /setspawn nether
            # Необходимо для того, чтобы снизить нагрузку на сервер при телепортациях так
            # как при каждой телепортации происходит эвент поиска ближайшего портала
            # и этим самым сильно нагружает сервер.
            enable-nether-spawn: true

            # Блокировка телепортации сущностей через порталы.
            block-entity-teleport: true

        # Возвращение в норму предметов у которых нелегальный стак. Пример: 64 тотема.
        overstack:
            enabled: true

            # Интервал для проверки инвентарей всех игроков на сервере.
            # Лучше ставить не меньше 20-30.
            # При просадках TPS это значение можно увеличить. (Бывает если онлайн больше 200)
            # time: 60 эквивалентно 3 секундам.
            time: 60

            # Список предметов которые могут иметь бесконечный стак.
            whitelist:
            - RABBIT_STEW
            - MUSHROOM_SOUP
            - BEETROOT_SOUP
            - CAKE

        # Заменяет предметы с большим количеством байт на блок земли.
        items:
            enabled: true
            limit-bytes: 4200
            shulker:
                limit-bytes: 14000
                block-books: true
                block-nested: false

    #    ▀██▀          ██                  ▄█▀▀▀▄█                                           
    #     ██    ▄▄▄   ▄▄▄  ▄▄ ▄▄▄          ██▄▄  ▀    ▄▄▄▄  ▄▄▄ ▄▄  ▄▄▄▄ ▄▄▄   ▄▄▄▄  ▄▄▄ ▄▄  
    #     ██  ▄█  ▀█▄  ██   ██  ██          ▀▀███▄  ▄█▄▄▄██  ██▀ ▀▀  ▀█▄  █  ▄█▄▄▄██  ██▀ ▀▀ 
    #     ██  ██   ██  ██   ██  ██   ████ ▄     ▀██ ██       ██       ▀█▄█   ██       ██     
    # ██ ▄█▀   ▀█▄▄█▀ ▄██▄ ▄██▄ ██▄       █▀▄▄▄▄█▀   ▀█▄▄▄▀ ▄██▄       ▀█     ▀█▄▄▄▀ ▄██▄    
    #  ▀▀▀                                                                                   

    # Подключение игрока к серверу.
    join-server:
        # Изменение количества ХП.
        # Диапазон: 1-1000.
        # default: 20 это 10 сердечек.
        custom-health:
            enabled: false

            # Хп игроков по умолчанию.
            default: 20

            # Группы игроков, ОБЯЗАТЕЛЬНО в порядке убывания.
            # Право для изменения количества
            # здоровья игроков - hcore.health.group.[group]
            # (обычным игрокам ничего выдавать не надо)
            groups:
                nether: 24
                diamond: 22

        # Изменение цвета ников.
        custom-nickname:
            enabled: false
            color:
                users: "&a"
                admins: "&c"
            disable-collisions: false

        # Всегда устанавливать максимальное количество хп.
        always-set-max-hp: false

        # Телепортация к спавну при заходе на сервер.
        spawn:

            # Телепортировать игрока на спавн при первом заходе на сервер.
            first: true

            # Телепортировать игрока на спавн каждый раз когда он заходит на сервер.
            always: false

        # Деопать всех игроков (и ленивых админов) которые не снимают с себя опку после того, как выходят с сервера.
        auto-deop: true

        # Флай при заходе на сервер.
        auto-fly: false

    # ▀██▀▀█▄             ▄              ▄          
    #  ██   ██   ▄▄▄▄   ▄██▄  ▄▄▄ ▄▄▄  ▄██▄   ▄▄▄▄  
    #  ██▀▀▀█▄  ▀▀ ▄██   ██    ██  ██   ██   ██▄ ▀  
    #  ██    ██ ▄█▀ ██   ██    ██  ██   ██   ▄ ▀█▄▄ 
    # ▄██▄▄▄█▀  ▀█▄▄▀█▀  ▀█▄▀  ▀█▄▄▀█▄  ▀█▄▀ █▀▄▄█▀ 

    # Настройка прыжков на блоках.
    # Необходим перезапуск сервера для включения/выключения этой функции.
    batuts:
        enabled: true

        # Вектор высоты и направления.
        vector:
            height: 3.5
            direction: 1

        # Настройка типов блоков для создания батута.
        block:
            up: STONE_PLATE
            down: DIAMOND_BLOCK

        # Звук при прыжке на батуте.
        sound:
            enabled: true
            play: ENTITY_ENDERDRAGON_FLAP

    # ▀██▀▀█▄                     ▄   ▀██
    #  ██   ██    ▄▄▄▄   ▄▄▄▄   ▄██▄   ██ ▄▄
    #  ██    ██ ▄█▄▄▄██ ▀▀ ▄██   ██    ██▀ ██
    #  ██    ██ ██      ▄█▀ ██   ██    ██  ██
    # ▄██▄▄▄█▀   ▀█▄▄▄▀ ▀█▄▄▀█▀  ▀█▄▀ ▄██▄ ██▄

    # Смерть игрока.
    death:
        # Телепортировать игрока на спавн.
        teleport-to-spawn: true

        # Шанс дропа предметов после смерти.
        # Необходим перезапуск сервера для включения/выключения этой функции.
        chance-on-drop-items:
            enabled: false

            # 0.5 = 50%
            chance:
                item: 0.5
                exp: 0.5

            # Количество опыта которое выпадет после смерти.
            amount-dropped-exp: 0.5

    #  ▄█▀▀▀▄█                                        ▀██▀▀▀▀█                  
    #  ██▄▄  ▀  ▄▄▄ ▄▄▄   ▄▄▄▄   ▄▄▄ ▄▄▄ ▄▄▄ ▄▄ ▄▄▄    ██  ▄      ▄▄▄ ▄   ▄▄▄ ▄ 
    #   ▀▀███▄   ██▀  ██ ▀▀ ▄██   ██  ██  █   ██  ██   ██▀▀█     ██ ██   ██ ██  
    # ▄     ▀██  ██    █ ▄█▀ ██    ███ ███    ██  ██   ██         █▀▀     █▀▀   
    # █▀▄▄▄▄█▀   ██▄▄▄▀  ▀█▄▄▀█▀    █   █    ▄██▄ ██▄ ▄██▄▄▄▄▄█  ▀████▄  ▀████▄ 
    #            ██                                             ▄█▄▄▄▄▀ ▄█▄▄▄▄▀ 
    #           ▀▀▀▀                                                            

    # Задержка при использовании яйца призыва моба.
    # Необходим перезапуск сервера для включения/выключения этой функции.
    cooldown-on-use-spawnegg:
        enabled: true

        # Время в секундах.
        time: 30

    #  ▄▄█▀▀██     ▄   ▀██                      
    # ▄█▀    ██  ▄██▄   ██ ▄▄     ▄▄▄▄  ▄▄▄ ▄▄  
    # ██      ██  ██    ██▀ ██  ▄█▄▄▄██  ██▀ ▀▀ 
    # ▀█▄     ██  ██    ██  ██  ██       ██     
    #  ▀▀█▄▄▄█▀   ▀█▄▀ ▄██▄ ██▄  ▀█▄▄▄▀ ▄██▄    

    # Остальные параметры.
    other-params:
        # Возможность писать на табличках используя цветовые теги &1 &2 &3 и т.д.
        colored-signs: true

        # Запретить игрокам видеть других игроков.
        block-see-other-players: false

        # Права hcore.bypass.* перестанут работать.
        # Рекомендуется держать включённым на серверах авторизации и хаба.
        disable-bypass-permissions: false

        # Скрытие сообщений о подключениях, ачивках и т.д. игроков.
        hide-messages:
            join: true
            leave: true
            death: true
            advancements: true

        # Больше информации можно узнать тут: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/Cancellable.html
        disable-events:
            PlayerInteractEvent: false
            BlockBreakEvent: false
            WeatherChangeEvent: false
            BlockPlaceEvent: false
            EntityDamageEvent: false
            PlayerInteractEntityEvent: false
            PlayerDropItemEvent: false
            EntityPickupItemEvent: false
            BlockFadeEvent: false
            BlockPhysicsEvent: false
            BlockFromToEvent: false
            BlockBurnEvent: false
            BlockIgniteEvent: false
            BlockSpreadEvent: false
            FoodLevelChangeEvent: false
            EntityExplodeEvent: false
            StructureGrowEvent: false
            PlayerChatTabCompleteEvent: false
            BlockFormEvent: false
            CreatureSpawnEvent: false
            LeavesDecayEvent: false