name: HCore
version: 0.3
main: ru.dehasher.hcore.HCore
api-version: 1.16

database: false
author: deHasher
website: https://dehasher.ru/

permissions:
  hcore.*:
    default: op
    children:
      - hcore.command.*
      - hcore.bypass.*
  hcore.command.*:
    default: op
    children:
      - hcore.command.spawn
      - hcore.command.spawn.others
      - hcore.command.spawn.exempt
      - hcore.command.setspawn
      - hcore.command.hreload
  hcore.bypass.*:
    default: op
    description: Позволяет обходить установленные плагином ограничения.
    children:
      - hcore.bypass.cooldown.*
      - hcore.bypass.commands.*
      - hcore.bypass.advertisement    # Позволяет отправлять рекламные ссылки в чат.
      - hcore.bypass.overstack        # Позволяет использовать оверстак предметы.
      - hcore.bypass.events           # Позволяет обходить выключенные эвенты.
  hcore.bypass.cooldown.*:
    default: op
    description: Позволяет обходить установленные плагином ограничения.
    children:
      - hcore.bypass.cooldown.egg     # Позволяет спавнить мобов с помощью яиц без задержки.
      - hcore.bypass.cooldown.message # Позволяет писать в чат без задержки.
  hcore.bypass.commands.*:
    default: op
    description: Позволяет обходить установленные плагином ограничения.
    children:
      - hcore.bypass.commands.all     # Позволяет отправлять команды, при disable-commands: true.
      - hcore.bypass.commands.colon   # Позволяет отправлять команды, при disable-colon: true.
  hcore.command.spawn:
    default: true
    description: Телепортироваться к точке спавна.
  hcore.health.group:
    default: op
    description: Позволяет установить себе кастомное количество здоровья.